### ISSUE TITLE
Many errors in dmesg

### ISSUE THREAD

**Issue by Mte90** [nealey/hdjd#5]
I got with dmesg too many lines like that with mixxx 2.0:
`usbfs: process 31363 (BulkReader DJ C) did not claim interface 1 before use`

**Comment by nealey** [comment]
Is process 31363 hdjd or mixxx?

**Comment by Mte90** [comment]
good point I will check asap!
Actually on mixxx detect the controller but I cannot interact with the application maybe is for this reason.

**Comment by nealey** [comment]
You might try running mixxx without hdjd, and see if you still get the
messages.

Unfortunately I wrote both hdjd and the code in mixxx that's likely causing
the error, but I don't have access to the hardware I need to fix it now.
Hopefully it's in mixxx, because there are other people maintaining that
code.

**Comment by Mte90** [comment]
Ok seems that now is not happening anymore but mixxx doesn't write any output on --controllerDebug with the daemon running.
So I think that the daemon has not problem but on dmesg I don't get anymore nothing so I guess that the ticket can be closed.
